from enum import StrEnum


class Intent(StrEnum):
    CANCEL_ORDER = "CANCEL_ORDER"
    ANALYTICS_QUERY = "ANALYTICS_QUERY"
    POLICY_SEARCH = "POLICY_SEARCH"
    VISION_RECEIPT_VALIDATE = "VISION_RECEIPT_VALIDATE"
    VISION_DAMAGE_ANALYSIS = "VISION_DAMAGE_ANALYSIS"
    CLARIFY = "CLARIFY"
    UNKNOWN = "UNKNOWN"


class ActionType(StrEnum):
    WRITE_MUTATION = "WRITE_MUTATION"
    SQL_ANALYTICS = "SQL_ANALYTICS"
    RAG_VISION = "RAG_VISION"
    CLARIFICATION = "CLARIFICATION"
    NOOP = "NOOP"
